package com.cloudstore.server.model.dto;

/**
 * Data Transfer Object for representing seller dashboard statistics.
**/
public class SellerDashboardStatsDTO {
    private double totalRevenue; // Total revenue generated by the seller
    private int totalOrders; // Total number of orders received
    private double averageOrderValue; // The average value per order
    private int productsSold; // Total count of distinct products sold
    private double totalSales; // Alternative representation of total sales
    private int lowStockProducts; // Count of seller's products with low stock

    /**
     * Default constructor for frameworks that require it.
    **/
    public SellerDashboardStatsDTO() {}

    /**
     * Constructor to initialize all fields.
     * @param totalRevenue Total revenue generated by the seller.
     * @param totalOrders Total number of orders received.
     * @param averageOrderValue The average value per order.
     * @param productsSold Total count of distinct products sold.
     * @param totalSales Alternative representation of total sales.
     * @param lowStockProducts Count of seller's products with low stock.
    **/
    public SellerDashboardStatsDTO(double totalRevenue, int totalOrders, double averageOrderValue, int productsSold, double totalSales, int lowStockProducts) {
        this.totalRevenue = totalRevenue;
        this.totalOrders = totalOrders;
        this.averageOrderValue = averageOrderValue;
        this.productsSold = productsSold;
        this.totalSales = totalSales;
        this.lowStockProducts = lowStockProducts;
    }

    /**
     * Gets the total revenue generated by the seller.
     * @return The totalRevenue.
    **/
    public double getTotalRevenue() { return totalRevenue; }

    /**
     * Sets the total revenue generated by the seller.
     * @param totalRevenue The totalRevenue.
    **/
    public void setTotalRevenue(double totalRevenue) { this.totalRevenue = totalRevenue; }
    /**
     * Gets the total number of orders received.
     * @return The totalOrders.
    **/
    public int getTotalOrders() { return totalOrders; }

    /**
     * Sets the total number of orders received.
     * @param totalOrders The totalOrders.
    **/
    public void setTotalOrders(int totalOrders) { this.totalOrders = totalOrders; }
    /**
     * Gets the the average value per order.
     * @return The averageOrderValue.
    **/
    public double getAverageOrderValue() { return averageOrderValue; }

    /**
     * Sets the the average value per order.
     * @param averageOrderValue The averageOrderValue.
    **/
    public void setAverageOrderValue(double averageOrderValue) { this.averageOrderValue = averageOrderValue; }
    /**
     * Gets the total count of distinct products sold.
     * @return The productsSold.
    **/
    public int getProductsSold() { return productsSold; }

    /**
     * Sets the total count of distinct products sold.
     * @param productsSold The productsSold.
    **/
    public void setProductsSold(int productsSold) { this.productsSold = productsSold; }
    /**
     * Gets the alternative representation of total sales.
     * @return The totalSales.
    **/
    public double getTotalSales() { return totalSales; }

    /**
     * Sets the alternative representation of total sales.
     * @param totalSales The totalSales.
    **/
    public void setTotalSales(double totalSales) { this.totalSales = totalSales; }
    /**
     * Gets the count of seller's products with low stock.
     * @return The lowStockProducts.
    **/
    public int getLowStockProducts() { return lowStockProducts; }

    /**
     * Sets the count of seller's products with low stock.
     * @param lowStockProducts The lowStockProducts.
    **/
    public void setLowStockProducts(int lowStockProducts) { this.lowStockProducts = lowStockProducts; }
}
